# Generated by Django 5.2 on 2026-01-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('dealer', 'Dealer'), ('service', 'Service'), ('employee', 'Employee')], default='employee', max_length=10),
        ),
    ]
